# Generated by Django 5.0 on 2023-12-07 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Lines',
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('serial_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('M', 'Machinery'), ('T', 'Tools'), ('V', 'Vehicles'), ('C', 'Computers'), ('E', 'Electronics')], max_length=2)),
                ('installation_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('lineId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.lines')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('frequency', models.CharField(choices=[('Av', 'Avant production'), ('AP', 'Après production'), ('J', 'Journalier'), ('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('TM', 'Trimestrielle'), ('SM', 'Semestrielle'), ('A', 'Annuelle'), ('2A', 'Chaque 2 ans'), ('3A', 'Chaque 3 ans'), ('4A', 'Chaque 4 ans'), ('5A', 'Chaque 5 ans'), ('6A', 'Chaque 6 ans'), ('N/A', 'inconnue')], default='Hebdomadaire', max_length=4)),
                ('mode', models.CharField(choices=[('A', 'Arrêt'), ('M', 'Marche'), ('M/A', 'Marche/Arrêt')], default='Marche/Arrêt', max_length=5)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('type', models.CharField(default='Preventive', max_length=10, validators=[django.core.validators.RegexValidator('Preventive')])),
                ('duration', models.DurationField()),
                ('intervention_type', models.CharField(choices=[('N', 'Nettoyage'), ('M', 'Maintenance'), ('L', 'Lubrification')], default='Maintenance', max_length=50)),
                ('ison', models.ManyToManyField(through='maintenance_plan.Contributors', to='maintenance_plan.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='contributors',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.maintenanceschedule'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance_plan.equipement')),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.section'),
        ),
    ]
