# Generated by Django 5.0 on 2024-01-04 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('Av', 'Avant production'), ('AP', 'Après production'), ('J', 'Journalier'), ('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('TM', 'Trimestrielle'), ('SM', 'Semestrielle'), ('A', 'Annuelle'), ('2A', 'Chaque 2 ans'), ('3A', 'Chaque 3 ans'), ('4A', 'Chaque 4 ans'), ('5A', 'Chaque 5 ans'), ('6A', 'Chaque 6 ans'), ('N/A', 'inconnue')], default='Hebdomadaire', max_length=4, null=True)),
                ('mode', models.CharField(blank=True, choices=[('A', 'Arrêt'), ('M', 'Marche'), ('AJ', 'Ajustage'), ('CIP', 'CIP'), ('N/A', 'inconnue')], default='Marche/Arrêt', max_length=5, null=True)),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('duration', models.DurationField(blank=True, null=True)),
                ('tools', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=75)),
                ('aids', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('serial_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('efficience', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('target', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Lines',
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('cleaning_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.cleaningtask')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='ison',
            field=models.ManyToManyField(through='maintenance_plan.Contributors', to='maintenance_plan.contributor'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='documents/')),
                ('equipement', models.ManyToManyField(blank=True, to='maintenance_plan.equipement')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='lineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.lines'),
        ),
        migrations.CreateModel(
            name='LubrificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('Av', 'Avant production'), ('AP', 'Après production'), ('J', 'Journalier'), ('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('TM', 'Trimestrielle'), ('SM', 'Semestrielle'), ('A', 'Annuelle'), ('2A', 'Chaque 2 ans'), ('3A', 'Chaque 3 ans'), ('4A', 'Chaque 4 ans'), ('5A', 'Chaque 5 ans'), ('6A', 'Chaque 6 ans'), ('N/A', 'inconnue')], default='Hebdomadaire', max_length=4, null=True)),
                ('mode', models.CharField(blank=True, choices=[('A', 'Arrêt'), ('M', 'Marche'), ('AJ', 'Ajustage'), ('CIP', 'CIP'), ('N/A', 'inconnue')], default='Marche/Arrêt', max_length=5, null=True)),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('duration', models.DurationField(blank=True, null=True)),
                ('tools', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=75)),
                ('lubrificant', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('ison', models.ManyToManyField(through='maintenance_plan.Contributors', to='maintenance_plan.contributor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contributors',
            name='lubrication_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.lubrificationtask'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance_plan.equipement')),
            ],
        ),
        migrations.AddField(
            model_name='lubrificationtask',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.part'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.part'),
        ),
        migrations.CreateModel(
            name='PreventiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('Av', 'Avant production'), ('AP', 'Après production'), ('J', 'Journalier'), ('H', 'Hebdomadaire'), ('M', 'Mensuelle'), ('TM', 'Trimestrielle'), ('SM', 'Semestrielle'), ('A', 'Annuelle'), ('2A', 'Chaque 2 ans'), ('3A', 'Chaque 3 ans'), ('4A', 'Chaque 4 ans'), ('5A', 'Chaque 5 ans'), ('6A', 'Chaque 6 ans'), ('N/A', 'inconnue')], default='Hebdomadaire', max_length=4, null=True)),
                ('mode', models.CharField(blank=True, choices=[('A', 'Arrêt'), ('M', 'Marche'), ('AJ', 'Ajustage'), ('CIP', 'CIP'), ('N/A', 'inconnue')], default='Marche/Arrêt', max_length=5, null=True)),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('duration', models.DurationField(blank=True, null=True)),
                ('tools', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=75)),
                ('criteria', models.CharField(blank=True, max_length=255, null=True)),
                ('ison', models.ManyToManyField(through='maintenance_plan.Contributors', to='maintenance_plan.contributor')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contributors',
            name='preventive_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_plan.preventivetask'),
        ),
    ]
