# Generated by Django 5.0 on 2024-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_plan', '0002_alter_document_equipement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='equipement',
            field=models.ManyToManyField(blank=True, to='maintenance_plan.equipement'),
        ),
    ]
