# Generated by Django 4.2.9 on 2024-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_plan', '0002_alter_preventivetask_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lubrificationtask',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='preventivetask',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
