# Generated by Django 4.2.9 on 2024-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_plan', '0003_cleaningtask_image_lubrificationtask_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtask',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field=50, null=True, upload_to='images/', width_field=50),
        ),
        migrations.AlterField(
            model_name='lubrificationtask',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field=50, null=True, upload_to='images/', width_field=50),
        ),
        migrations.AlterField(
            model_name='preventivetask',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field=50, null=True, upload_to='images/', width_field=50),
        ),
    ]
