# Generated by Django 5.0 on 2024-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_plan', '0003_alter_document_equipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lubrificationtask',
            name='quantity',
        ),
        migrations.AddField(
            model_name='part',
            name='document_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
