# Generated by Django 4.2.9 on 2024-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_plan', '0005_cleaningtask_image_height_cleaningtask_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
    ]
